### ISSUE TITLE
security_dashboard to blueprint.yaml

### ISSUE THREAD

**Issue by stepsolar** [LRvdLinden/security_dashboard_dd_addon#1]
Salutations,
how can i test the security_dashboard project in blueprint.yaml V3?
Thanks

**Comment by LRvdLinden** [comment]
Security addon is only till v2.7

**Comment by stepsolar** [comment]
Thank you for answering.
Yours is a good job, I'm sorry not to be able to use it in V3.
What could I use as an alarm in V3?
There is a way to convert your work
as so many projects have been converted to V3.
Thanks

**Comment by LRvdLinden** [comment]
You can use the standard lovelace alarm card.
